version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  matching-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - PORT=8080
      - REDIS_URL=redis:6379
    
volumes:
  redis_data: