services:
  postgres:
    image: postgres:16-alpine
    container_name: question-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=questiondb
    ports:
      - "5432:5432"
    volumes:
      # Named volume for data (will be empty on first run)
      - postgres_data:/var/lib/postgresql/data
      # Init script to restore seed data on first startup
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      # Seed data file
      - ./db-backups/seed-initial.dump:/seed-initial.dump:ro
      # Backup location for manual backups
      - ./db-backups:/backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d questiondb"]
      interval: 10s
      timeout: 5s
      retries: 5

  question-service:
    build:
      context: .
    image: question-service:latest
    container_name: question-service
    environment:
      - PORT=8080
      - NODE_ENV=production
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/questiondb
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: