name: AI Service CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: uv sync

      - name: Lint
        run: uv run ruff check ./backend/ai-service
        continue-on-error: true

      - name: Build
        run: uv run build
