name: Matching Service CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.5
          cache: true

      - name: Install dependencies
        run: go mod tidy
        working-directory: backend/matching-service

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: backend/matching-service
          args: --timeout=5m
        continue-on-error: true

      - name: Build
        run: go build -o .
        working-directory: backend/matching-service

      - name: Run tests
        run: go test -v .
        working-directory: backend/matching-service
